servers:
  dkr: servers/dkr
  ersatz: servers/ersatz
  prompt: servers/prompt
  local_llm: servers/local_llm

pipeline:
  # 1. Initialization
  - dkr.init_agent
  - ersatz.init_agent
  - local_llm.init_client
  
  # 2. Retrieval
  - dkr.lookup_exact:
      output:
        results: dkr_results
  - ersatz.semantic_search:
      output:
        chunks: ersatz_chunks
  
  # 3. Prompt Synthesis
  - prompt.synthesis:
      input:
        dkr_results: dkr_results
        ersatz_chunks: ersatz_chunks
      output:
        prompt_ls: synthesized_prompt # "prompt_ls" is standard output for prompt tools

  # 4. Generation
  - local_llm.generate:
      input:
        prompt: $synthesized_prompt # $ denotes a variable reference from previous steps
